# Generated by Django 4.2 on 2023-04-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrator',
            table='administrator',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='level',
            table='level',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='pricepolicy',
            table='price_policy',
        ),
        migrations.AlterModelTable(
            name='transactionrecord',
            table='transaction_record',
        ),
    ]
